// Currency data with 150+ world currencies and mock exchange rates

export const CURRENCIES = {
  USD: { name: "US Dollar", symbol: "$", rate: 1 },
  EUR: { name: "Euro", symbol: "€", rate: 0.92 },
  GBP: { name: "British Pound", symbol: "£", rate: 0.79 },
  JPY: { name: "Japanese Yen", symbol: "¥", rate: 149.50 },
  CNY: { name: "Chinese Yuan", symbol: "¥", rate: 7.24 },
  INR: { name: "Indian Rupee", symbol: "₹", rate: 83.12 },
  AUD: { name: "Australian Dollar", symbol: "A$", rate: 1.53 },
  CAD: { name: "Canadian Dollar", symbol: "C$", rate: 1.36 },
  CHF: { name: "Swiss Franc", symbol: "Fr", rate: 0.88 },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$", rate: 7.82 },
  SGD: { name: "Singapore Dollar", symbol: "S$", rate: 1.34 },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$", rate: 1.63 },
  KRW: { name: "South Korean Won", symbol: "₩", rate: 1325.00 },
  MXN: { name: "Mexican Peso", symbol: "Mex$", rate: 17.15 },
  BRL: { name: "Brazilian Real", symbol: "R$", rate: 4.97 },
  ZAR: { name: "South African Rand", symbol: "R", rate: 18.63 },
  RUB: { name: "Russian Ruble", symbol: "₽", rate: 91.50 },
  SEK: { name: "Swedish Krona", symbol: "kr", rate: 10.42 },
  NOK: { name: "Norwegian Krone", symbol: "kr", rate: 10.55 },
  DKK: { name: "Danish Krone", symbol: "kr", rate: 6.87 },
  PLN: { name: "Polish Zloty", symbol: "zł", rate: 4.03 },
  CZK: { name: "Czech Koruna", symbol: "Kč", rate: 22.85 },
  HUF: { name: "Hungarian Forint", symbol: "Ft", rate: 356.00 },
  RON: { name: "Romanian Leu", symbol: "lei", rate: 4.58 },
  BGN: { name: "Bulgarian Lev", symbol: "лв", rate: 1.80 },
  HRK: { name: "Croatian Kuna", symbol: "kn", rate: 6.93 },
  ISK: { name: "Icelandic Króna", symbol: "kr", rate: 137.00 },
  TRY: { name: "Turkish Lira", symbol: "₺", rate: 28.90 },
  THB: { name: "Thai Baht", symbol: "฿", rate: 35.20 },
  MYR: { name: "Malaysian Ringgit", symbol: "RM", rate: 4.69 },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp", rate: 15450.00 },
  PHP: { name: "Philippine Peso", symbol: "₱", rate: 56.20 },
  VND: { name: "Vietnamese Dong", symbol: "₫", rate: 24350.00 },
  TWD: { name: "Taiwan Dollar", symbol: "NT$", rate: 31.80 },
  PKR: { name: "Pakistani Rupee", symbol: "₨", rate: 281.00 },
  BDT: { name: "Bangladeshi Taka", symbol: "৳", rate: 110.00 },
  LKR: { name: "Sri Lankan Rupee", symbol: "Rs", rate: 323.00 },
  NPR: { name: "Nepalese Rupee", symbol: "₨", rate: 133.00 },
  MMK: { name: "Myanmar Kyat", symbol: "K", rate: 2100.00 },
  KHR: { name: "Cambodian Riel", symbol: "៛", rate: 4100.00 },
  LAK: { name: "Lao Kip", symbol: "₭", rate: 20800.00 },
  BND: { name: "Brunei Dollar", symbol: "B$", rate: 1.34 },
  AED: { name: "UAE Dirham", symbol: "د.إ", rate: 3.67 },
  SAR: { name: "Saudi Riyal", symbol: "﷼", rate: 3.75 },
  QAR: { name: "Qatari Riyal", symbol: "﷼", rate: 3.64 },
  KWD: { name: "Kuwaiti Dinar", symbol: "د.ك", rate: 0.31 },
  BHD: { name: "Bahraini Dinar", symbol: "BD", rate: 0.38 },
  OMR: { name: "Omani Rial", symbol: "﷼", rate: 0.38 },
  JOD: { name: "Jordanian Dinar", symbol: "JD", rate: 0.71 },
  ILS: { name: "Israeli Shekel", symbol: "₪", rate: 3.68 },
  EGP: { name: "Egyptian Pound", symbol: "E£", rate: 30.90 },
  LBP: { name: "Lebanese Pound", symbol: "ل.ل", rate: 89500.00 },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د", rate: 1310.00 },
  IRR: { name: "Iranian Rial", symbol: "﷼", rate: 42000.00 },
  SYP: { name: "Syrian Pound", symbol: "£S", rate: 13000.00 },
  YER: { name: "Yemeni Rial", symbol: "﷼", rate: 250.00 },
  NGN: { name: "Nigerian Naira", symbol: "₦", rate: 780.00 },
  GHS: { name: "Ghanaian Cedi", symbol: "₵", rate: 12.30 },
  KES: { name: "Kenyan Shilling", symbol: "KSh", rate: 153.00 },
  TZS: { name: "Tanzanian Shilling", symbol: "TSh", rate: 2510.00 },
  UGX: { name: "Ugandan Shilling", symbol: "USh", rate: 3780.00 },
  ETB: { name: "Ethiopian Birr", symbol: "Br", rate: 56.50 },
  MAD: { name: "Moroccan Dirham", symbol: "د.م.", rate: 10.05 },
  TND: { name: "Tunisian Dinar", symbol: "د.ت", rate: 3.12 },
  DZD: { name: "Algerian Dinar", symbol: "د.ج", rate: 134.50 },
  LYD: { name: "Libyan Dinar", symbol: "ل.د", rate: 4.82 },
  SDG: { name: "Sudanese Pound", symbol: "ج.س.", rate: 601.00 },
  XOF: { name: "West African CFA", symbol: "CFA", rate: 603.50 },
  XAF: { name: "Central African CFA", symbol: "FCFA", rate: 603.50 },
  RWF: { name: "Rwandan Franc", symbol: "FRw", rate: 1240.00 },
  BIF: { name: "Burundian Franc", symbol: "FBu", rate: 2840.00 },
  CDF: { name: "Congolese Franc", symbol: "FC", rate: 2680.00 },
  ZMW: { name: "Zambian Kwacha", symbol: "ZK", rate: 23.50 },
  MWK: { name: "Malawian Kwacha", symbol: "MK", rate: 1690.00 },
  MZN: { name: "Mozambican Metical", symbol: "MT", rate: 63.50 },
  AOA: { name: "Angolan Kwanza", symbol: "Kz", rate: 830.00 },
  BWP: { name: "Botswana Pula", symbol: "P", rate: 13.60 },
  NAD: { name: "Namibian Dollar", symbol: "N$", rate: 18.63 },
  SCR: { name: "Seychellois Rupee", symbol: "₨", rate: 13.70 },
  MUR: { name: "Mauritian Rupee", symbol: "₨", rate: 44.50 },
  MGF: { name: "Malagasy Ariary", symbol: "Ar", rate: 4520.00 },
  CLP: { name: "Chilean Peso", symbol: "$", rate: 880.00 },
  COP: { name: "Colombian Peso", symbol: "$", rate: 3950.00 },
  PEN: { name: "Peruvian Sol", symbol: "S/.", rate: 3.72 },
  ARS: { name: "Argentine Peso", symbol: "$", rate: 350.00 },
  UYU: { name: "Uruguayan Peso", symbol: "$U", rate: 39.20 },
  PYG: { name: "Paraguayan Guarani", symbol: "₲", rate: 7280.00 },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs.", rate: 6.91 },
  VES: { name: "Venezuelan Bolívar", symbol: "Bs.S", rate: 36.20 },
  GYD: { name: "Guyanese Dollar", symbol: "G$", rate: 209.00 },
  SRD: { name: "Surinamese Dollar", symbol: "SRD", rate: 38.20 },
  TTD: { name: "Trinidad Dollar", symbol: "TT$", rate: 6.78 },
  JMD: { name: "Jamaican Dollar", symbol: "J$", rate: 155.00 },
  BBD: { name: "Barbadian Dollar", symbol: "Bds$", rate: 2.00 },
  BSD: { name: "Bahamian Dollar", symbol: "B$", rate: 1.00 },
  BZD: { name: "Belize Dollar", symbol: "BZ$", rate: 2.02 },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q", rate: 7.83 },
  HNL: { name: "Honduran Lempira", symbol: "L", rate: 24.70 },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$", rate: 36.60 },
  CRC: { name: "Costa Rican Colón", symbol: "₡", rate: 530.00 },
  PAB: { name: "Panamanian Balboa", symbol: "B/.", rate: 1.00 },
  DOP: { name: "Dominican Peso", symbol: "RD$", rate: 56.80 },
  HTG: { name: "Haitian Gourde", symbol: "G", rate: 132.00 },
  CUP: { name: "Cuban Peso", symbol: "$MN", rate: 24.00 },
  KZT: { name: "Kazakh Tenge", symbol: "₸", rate: 462.00 },
  UZS: { name: "Uzbekistani Som", symbol: "сўм", rate: 12300.00 },
  TMT: { name: "Turkmen Manat", symbol: "T", rate: 3.50 },
  KGS: { name: "Kyrgyz Som", symbol: "сом", rate: 89.30 },
  TJS: { name: "Tajikistani Somoni", symbol: "SM", rate: 10.95 },
  GEL: { name: "Georgian Lari", symbol: "₾", rate: 2.68 },
  AMD: { name: "Armenian Dram", symbol: "֏", rate: 386.00 },
  AZN: { name: "Azerbaijani Manat", symbol: "₼", rate: 1.70 },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴", rate: 37.50 },
  BYN: { name: "Belarusian Ruble", symbol: "Br", rate: 3.27 },
  MDL: { name: "Moldovan Leu", symbol: "L", rate: 17.80 },
  RSD: { name: "Serbian Dinar", symbol: "дин.", rate: 108.00 },
  BAM: { name: "Bosnia Mark", symbol: "KM", rate: 1.80 },
  MKD: { name: "Macedonian Denar", symbol: "ден", rate: 56.70 },
  ALL: { name: "Albanian Lek", symbol: "L", rate: 95.50 },
  MNT: { name: "Mongolian Tugrik", symbol: "₮", rate: 3440.00 },
  AFN: { name: "Afghan Afghani", symbol: "؋", rate: 73.50 },
  FJD: { name: "Fijian Dollar", symbol: "FJ$", rate: 2.24 },
  PGK: { name: "Papua New Guinean Kina", symbol: "K", rate: 3.72 },
  WST: { name: "Samoan Tala", symbol: "WS$", rate: 2.72 },
  TOP: { name: "Tongan Paʻanga", symbol: "T$", rate: 2.35 },
  VUV: { name: "Vanuatu Vatu", symbol: "VT", rate: 119.00 },
  SBD: { name: "Solomon Islands Dollar", symbol: "SI$", rate: 8.42 },
  XPF: { name: "CFP Franc", symbol: "₣", rate: 109.80 },
  MVR: { name: "Maldivian Rufiyaa", symbol: "Rf", rate: 15.40 },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu.", rate: 83.12 },
  SOS: { name: "Somali Shilling", symbol: "Sh", rate: 571.00 },
  DJF: { name: "Djiboutian Franc", symbol: "Fdj", rate: 178.00 },
  ERN: { name: "Eritrean Nakfa", symbol: "Nfk", rate: 15.00 },
  GMD: { name: "Gambian Dalasi", symbol: "D", rate: 67.00 },
  GNF: { name: "Guinean Franc", symbol: "FG", rate: 8600.00 },
  SLL: { name: "Sierra Leonean Leone", symbol: "Le", rate: 22800.00 },
  LRD: { name: "Liberian Dollar", symbol: "L$", rate: 188.00 },
  CVE: { name: "Cape Verdean Escudo", symbol: "Esc", rate: 101.50 },
  STN: { name: "São Tomé Dobra", symbol: "Db", rate: 22.60 },
  SZL: { name: "Eswatini Lilangeni", symbol: "E", rate: 18.63 },
  LSL: { name: "Lesotho Loti", symbol: "L", rate: 18.63 },
  KMF: { name: "Comorian Franc", symbol: "CF", rate: 453.00 },
  MOP: { name: "Macanese Pataca", symbol: "MOP$", rate: 8.06 },
  KPW: { name: "North Korean Won", symbol: "₩", rate: 900.00 },
  CUC: { name: "Cuban Convertible", symbol: "$", rate: 1.00 },
  XCD: { name: "East Caribbean Dollar", symbol: "EC$", rate: 2.70 },
  BMD: { name: "Bermudian Dollar", symbol: "$", rate: 1.00 },
  KYD: { name: "Cayman Islands Dollar", symbol: "CI$", rate: 0.83 },
  AWG: { name: "Aruban Florin", symbol: "ƒ", rate: 1.79 },
  ANG: { name: "Netherlands Antillean Guilder", symbol: "ƒ", rate: 1.79 },
  FKP: { name: "Falkland Islands Pound", symbol: "£", rate: 0.79 },
  GIP: { name: "Gibraltar Pound", symbol: "£", rate: 0.79 },
  SHP: { name: "Saint Helena Pound", symbol: "£", rate: 0.79 },
  XAU: { name: "Gold (troy oz)", symbol: "XAU", rate: 0.0005 },
  XAG: { name: "Silver (troy oz)", symbol: "XAG", rate: 0.042 },
  BTC: { name: "Bitcoin", symbol: "₿", rate: 0.000024 },
};

// Fetch live rates from a free API
const RATE_API = "https://open.er-api.com/v6/latest/USD";

export async function fetchLiveRates() {
  const res = await fetch(RATE_API);
  if (!res.ok) return null;
  const data = await res.json();
  if (data.result !== "success") return null;
  return data.rates;
}

export function convertCurrency(amount, fromCode, toCode, rates) {
  const fromRate = rates[fromCode];
  const toRate = rates[toCode];
  if (!fromRate || !toRate) return NaN;
  return (amount / fromRate) * toRate;
}

export function getCurrencyList() {
  return Object.entries(CURRENCIES).map(([code, info]) => ({
    code,
    name: info.name,
    symbol: info.symbol,
  }));
}

export function getMockRates() {
  const rates = {};
  Object.entries(CURRENCIES).forEach(([code, info]) => {
    rates[code] = info.rate;
  });
  return rates;
}